import type { FaqRecord, FaqTopic } from '@/types/models'

export const faqCategories: FaqTopic[] = [
  'general',
  'passeport',
  'cnie',
  'attestation',
  'etat-civil',
  'legalisation',
  'justice',
  'vehicule',
  'fiscalite',
  'etrangers',
  'urbanisme',
  'entreprise',
  'citoyennete',
  'product',
]

export const faqOrder = [
  'faq-passeport-annexe-responsable',
  'faq-passeport-nimporte-quelle-annexe',
  'faq-renouvellement-cnie-ou-aller',
  'faq-duplicata-cin-ou-aller',
  'faq-zone-vs-autorite',
  'faq-que-faire-si-zone-non-detectee',
  'faq-changer-zone-manuellement',
  'faq-documents-attestation-residence',
  'faq-attestation-meme-jour',
  'faq-acte-naissance-autre-ville',
  'faq-watiqa-remplace-guichet',
  'faq-legalisation-sans-rendez-vous',
  'faq-legalisation-vs-copie-conforme',
  'faq-livret-famille-ou-aller',
  'faq-acte-deces-quelle-administration',
  'faq-casier-en-ligne',
  'faq-permis-ville-ou-annexe',
  'faq-carte-grise-ou-aller',
  'faq-vignette-deplacement',
  'faq-carte-sejour-ou-commencer',
  'faq-permis-construire-lieu-bien',
  'faq-auto-entrepreneur-vs-registre-commerce',
  'faq-inscription-electorale-ou-aller',
  'faq-houma-couvre-quelles-villes',
  'faq-houma-preuve-officielle',
] as const

export const faqs: Record<string, FaqRecord> = {
  'faq-passeport-annexe-responsable': {
    id: 'faq-passeport-annexe-responsable',
    slug: 'quelle-annexe-est-responsable-pour-mon-passeport',
    topic: 'passeport',
    questionFr: 'Comment savoir quelle annexe est responsable pour mon passeport ?',
    questionAr: 'كيف أعرف أي ملحقة مسؤولة عن جواز سفري؟',
    answerFr: 'Sur Houma, la zone sélectionnée sert de contexte. La réponse finale reste l’autorité responsable affichée sur la page du passeport.',
    answerAr: 'في Houma تُستعمل المنطقة المختارة كسياق. أما الجواب النهائي فيبقى الجهة المسؤولة المعروضة في صفحة جواز السفر.',
    relatedServiceSlugs: ['passeport-marocain'],
    relatedCitySlugs: [],
    keywords: ['annexe passeport', 'autorite responsable passeport', 'passeport quartier'],
    isGlobal: true,
    priority: 1,
  },
  'faq-passeport-nimporte-quelle-annexe': {
    id: 'faq-passeport-nimporte-quelle-annexe',
    slug: 'puis-je-demander-mon-passeport-dans-nimporte-quelle-annexe',
    topic: 'passeport',
    questionFr: 'Puis-je demander mon passeport dans n’importe quelle annexe ?',
    questionAr: 'هل يمكنني طلب جواز السفر في أي ملحقة؟',
    answerFr: 'En pratique, le dépôt dépend de l’autorité locale compétente liée à votre résidence. Houma aide à repérer ce point de départ.',
    answerAr: 'عمليا يرتبط الإيداع بالجهة المحلية المختصة المرتبطة بمحل السكن. تساعد Houma على تحديد نقطة الانطلاق.',
    relatedServiceSlugs: ['passeport-marocain'],
    relatedCitySlugs: [],
    keywords: ['passeport annexe residence', 'ou faire passeport'],
    isGlobal: true,
    priority: 1,
  },
  'faq-renouvellement-cnie-ou-aller': {
    id: 'faq-renouvellement-cnie-ou-aller',
    slug: 'ou-aller-pour-un-renouvellement-de-cnie',
    topic: 'cnie',
    questionFr: 'Où aller pour un renouvellement de CNIE ?',
    questionAr: 'إلى أين أتوجه لتجديد البطاقة الوطنية؟',
    answerFr: 'Commencez par la page du service. La ville peut suffire comme point de départ, mais une zone peut affiner l’autorité responsable.',
    answerAr: 'ابدأ من صفحة الخدمة. قد تكفي المدينة كنقطة انطلاق، لكن المنطقة قد تجعل الجهة المسؤولة أدق.',
    relatedServiceSlugs: ['renouvellement-cnie'],
    relatedCitySlugs: [],
    keywords: ['renouvellement cnie ou aller', 'annexe cnie'],
    isGlobal: true,
    priority: 1,
  },
  'faq-duplicata-cin-ou-aller': {
    id: 'faq-duplicata-cin-ou-aller',
    slug: 'ou-aller-pour-un-duplicata-de-cin',
    topic: 'cnie',
    questionFr: 'Où aller pour un duplicata de CIN ?',
    questionAr: 'إلى أين أتوجه لاستخراج نظير البطاقة الوطنية؟',
    answerFr: 'Le duplicata CIN suit une logique proche des démarches d’identité locales. Houma affiche l’autorité responsable plutôt qu’un simple bureau proche.',
    answerAr: 'يتبع نظير البطاقة الوطنية منطقا قريبا من إجراءات الهوية المحلية. وتعرض Houma الجهة المسؤولة بدل مجرد مكتب قريب.',
    relatedServiceSlugs: ['duplicata-cin'],
    relatedCitySlugs: [],
    keywords: ['duplicata cin', 'perte cin ou aller'],
    isGlobal: true,
    priority: 1,
  },
  'faq-zone-vs-autorite': {
    id: 'faq-zone-vs-autorite',
    slug: 'quelle-difference-entre-zone-selectionnee-et-autorite-responsable',
    topic: 'general',
    questionFr: 'Quelle différence entre zone sélectionnée et autorité responsable ?',
    questionAr: 'ما الفرق بين المنطقة المختارة والجهة المسؤولة؟',
    answerFr: 'La zone sélectionnée aide à préciser la réponse locale. L’autorité responsable est la réponse finale affichée sur la page du service.',
    answerAr: 'المنطقة المختارة تساعد على جعل الجواب المحلي أدق. أما الجهة المسؤولة فهي الجواب النهائي المعروض في صفحة الخدمة.',
    relatedServiceSlugs: ['passeport-marocain', 'renouvellement-cnie', 'attestation-residence', 'legalisation-signature'],
    relatedCitySlugs: [],
    keywords: ['zone selectionnee', 'autorite responsable', 'difference zone autorite'],
    isGlobal: true,
    priority: 1,
  },
  'faq-que-faire-si-zone-non-detectee': {
    id: 'faq-que-faire-si-zone-non-detectee',
    slug: 'que-faire-si-ma-zone-nest-pas-detectee',
    topic: 'general',
    questionFr: 'Que faire si ma zone n’est pas détectée ?',
    questionAr: 'ماذا أفعل إذا لم يتم كشف منطقتي؟',
    answerFr: 'Vous pouvez continuer avec une réponse au niveau ville, puis ajouter une zone si vous souhaitez une réponse locale plus précise.',
    answerAr: 'يمكنك المتابعة بجواب على مستوى المدينة ثم إضافة منطقة إذا كنت تريد جوابا محليا أكثر دقة.',
    relatedServiceSlugs: ['passeport-marocain', 'attestation-residence', 'legalisation-signature', 'permis-construire'],
    relatedCitySlugs: [],
    keywords: ['zone non detectee', 'ajouter une zone'],
    isGlobal: true,
    priority: 1,
  },
  'faq-changer-zone-manuellement': {
    id: 'faq-changer-zone-manuellement',
    slug: 'puis-je-changer-ma-zone-manuellement',
    topic: 'general',
    questionFr: 'Puis-je changer ma zone manuellement ?',
    questionAr: 'هل يمكنني تغيير منطقتي يدويا؟',
    answerFr: 'Oui. Depuis la page du service, utilisez Ajouter une zone ou Changer la zone sans quitter la démarche en cours.',
    answerAr: 'نعم. من صفحة الخدمة استعمل إضافة منطقة أو تغيير المنطقة دون مغادرة الإجراء الجاري.',
    relatedServiceSlugs: ['passeport-marocain', 'renouvellement-cnie', 'attestation-residence', 'legalisation-signature'],
    relatedCitySlugs: [],
    keywords: ['changer zone manuellement', 'modifier zone'],
    isGlobal: true,
    priority: 2,
  },
  'faq-documents-attestation-residence': {
    id: 'faq-documents-attestation-residence',
    slug: 'quels-documents-faut-il-pour-une-attestation-de-residence',
    topic: 'attestation',
    questionFr: 'Quels documents faut-il pour une attestation de résidence ?',
    questionAr: 'ما الوثائق المطلوبة لشهادة السكنى؟',
    answerFr: 'La liste peut varier, mais elle inclut souvent une pièce d’identité valide et un justificatif de domicile récent. Vérifiez la page du service et la source officielle.',
    answerAr: 'قد تختلف اللائحة، لكنها تشمل غالبا وثيقة هوية سارية وإثبات سكن حديث. تحقق من صفحة الخدمة والمصدر الرسمي.',
    relatedServiceSlugs: ['attestation-residence'],
    relatedCitySlugs: [],
    keywords: ['documents attestation residence', 'pieces attestation residence'],
    isGlobal: true,
    priority: 1,
  },
  'faq-attestation-meme-jour': {
    id: 'faq-attestation-meme-jour',
    slug: 'lattestation-de-residence-est-elle-delivree-le-jour-meme',
    topic: 'attestation',
    questionFr: 'L’attestation de résidence est-elle délivrée le jour même ?',
    questionAr: 'هل تسلم شهادة السكنى في نفس اليوم؟',
    answerFr: 'Souvent oui, mais cela dépend du guichet, des pièces et du contrôle local. Houma affiche un repère, pas une garantie absolue.',
    answerAr: 'غالبا نعم، لكن ذلك يعتمد على الشباك والوثائق والمراجعة المحلية. تعرض Houma مؤشرا لا ضمانا مطلقا.',
    relatedServiceSlugs: ['attestation-residence'],
    relatedCitySlugs: [],
    keywords: ['delai attestation residence', 'attestation meme jour'],
    isGlobal: true,
    priority: 2,
  },
  'faq-acte-naissance-autre-ville': {
    id: 'faq-acte-naissance-autre-ville',
    slug: 'ou-demander-un-acte-de-naissance-si-je-suis-ne-dans-une-autre-ville',
    topic: 'etat-civil',
    questionFr: 'Où demander un acte de naissance si je suis né dans une autre ville ?',
    questionAr: 'أين أطلب عقد الازدياد إذا كنت مولودا في مدينة أخرى؟',
    answerFr: 'L’acte de naissance dépend du lieu d’état civil. Si votre situation le permet, Watiqa peut parfois éviter un déplacement.',
    answerAr: 'يعتمد عقد الازدياد على مكان الحالة المدنية. وإذا كانت وضعيتك تسمح، فقد تجنبك وثيقة التنقل أحيانا.',
    relatedServiceSlugs: ['acte-naissance'],
    relatedCitySlugs: [],
    keywords: ['acte naissance autre ville', 'ou demander acte naissance'],
    isGlobal: true,
    priority: 1,
  },
  'faq-watiqa-remplace-guichet': {
    id: 'faq-watiqa-remplace-guichet',
    slug: 'watiqa-remplace-t-il-toujours-le-guichet',
    topic: 'etat-civil',
    questionFr: 'Watiqa remplace-t-il toujours le guichet ?',
    questionAr: 'هل تعوض وثيقة دائما الشباك؟',
    answerFr: 'Non. Watiqa aide pour certaines demandes d’état civil, mais certaines situations nécessitent encore un passage au guichet.',
    answerAr: 'لا. تساعد وثيقة في بعض طلبات الحالة المدنية، لكن بعض الحالات ما زالت تتطلب المرور عبر الشباك.',
    relatedServiceSlugs: ['acte-naissance', 'livret-famille', 'acte-deces'],
    relatedCitySlugs: [],
    keywords: ['watiqa guichet', 'watiqa etat civil'],
    isGlobal: true,
    priority: 1,
  },
  'faq-legalisation-sans-rendez-vous': {
    id: 'faq-legalisation-sans-rendez-vous',
    slug: 'puis-je-legaliser-une-signature-sans-rendez-vous',
    topic: 'legalisation',
    questionFr: 'Puis-je légaliser une signature sans rendez-vous ?',
    questionAr: 'هل يمكنني المصادقة على الإمضاء دون موعد؟',
    answerFr: 'Souvent oui, mais cela dépend de l’organisation locale. Vérifiez les horaires et préparez le document original ainsi que votre pièce d’identité.',
    answerAr: 'غالبا نعم، لكن ذلك يعتمد على التنظيم المحلي. تحقق من التوقيت وأحضر الوثيقة الأصلية ووثيقة هويتك.',
    relatedServiceSlugs: ['legalisation-signature'],
    relatedCitySlugs: [],
    keywords: ['legalisation sans rendez-vous', 'horaires legalisation'],
    isGlobal: true,
    priority: 1,
  },
  'faq-legalisation-vs-copie-conforme': {
    id: 'faq-legalisation-vs-copie-conforme',
    slug: 'quelle-difference-entre-legalisation-de-signature-et-copie-conforme',
    topic: 'legalisation',
    questionFr: 'Quelle différence entre légalisation de signature et copie conforme ?',
    questionAr: 'ما الفرق بين المصادقة على الإمضاء ونسخة مطابقة للأصل؟',
    answerFr: 'La légalisation valide l’identité du signataire au moment de la signature. La copie conforme concerne la conformité d’une copie à l’original lorsque la procédure le prévoit.',
    answerAr: 'المصادقة تثبت هوية الموقع وقت التوقيع. أما النسخة المطابقة فتتعلق بمطابقة النسخة للأصل عندما تنص المسطرة على ذلك.',
    relatedServiceSlugs: ['legalisation-signature'],
    relatedCitySlugs: [],
    keywords: ['legalisation signature copie conforme'],
    isGlobal: true,
    priority: 2,
  },
  'faq-livret-famille-ou-aller': {
    id: 'faq-livret-famille-ou-aller',
    slug: 'ou-se-renseigner-pour-le-livret-de-famille',
    topic: 'etat-civil',
    questionFr: 'Où se renseigner pour le livret de famille ?',
    questionAr: 'أين أستفسر بخصوص الدفتر العائلي؟',
    answerFr: 'Commencez par la page du service et par la logique d’état civil concernée. Selon la situation, le bureau compétent peut dépendre du contexte familial et administratif.',
    answerAr: 'ابدأ بصفحة الخدمة وبمنطق الحالة المدنية المعني. ووفق الوضعية قد يعتمد المكتب المختص على السياق العائلي والإداري.',
    relatedServiceSlugs: ['livret-famille'],
    relatedCitySlugs: [],
    keywords: ['livret de famille ou aller', 'etat civil livret famille'],
    isGlobal: true,
    priority: 2,
  },
  'faq-acte-deces-quelle-administration': {
    id: 'faq-acte-deces-quelle-administration',
    slug: 'quelle-administration-pour-un-acte-de-deces',
    topic: 'etat-civil',
    questionFr: 'Quelle administration pour un acte de décès ?',
    questionAr: 'ما الإدارة المختصة بعقد الوفاة؟',
    answerFr: 'La réponse dépend du contexte d’état civil concerné. Vérifiez la page du service et la source officielle avant de vous déplacer.',
    answerAr: 'يعتمد الجواب على سياق الحالة المدنية المعني. تحقق من صفحة الخدمة والمصدر الرسمي قبل التنقل.',
    relatedServiceSlugs: ['acte-deces'],
    relatedCitySlugs: [],
    keywords: ['acte deces administration', 'ou demander acte de deces'],
    isGlobal: true,
    priority: 2,
  },
  'faq-casier-en-ligne': {
    id: 'faq-casier-en-ligne',
    slug: 'le-casier-judiciaire-peut-il-se-demander-en-ligne',
    topic: 'justice',
    questionFr: 'Le casier judiciaire peut-il se demander en ligne ?',
    questionAr: 'هل يمكن طلب السجل العدلي عبر الإنترنت؟',
    answerFr: 'Une partie du parcours peut être en ligne selon la procédure officielle. Utilisez toujours le lien officiel affiché sur la page du service.',
    answerAr: 'قد يكون جزء من المسار عبر الإنترنت حسب المسطرة الرسمية. استعمل دائما الرابط الرسمي المعروض في صفحة الخدمة.',
    relatedServiceSlugs: ['casier-judiciaire'],
    relatedCitySlugs: [],
    keywords: ['casier judiciaire en ligne', 'casier lien officiel'],
    isGlobal: true,
    priority: 1,
  },
  'faq-permis-ville-ou-annexe': {
    id: 'faq-permis-ville-ou-annexe',
    slug: 'le-permis-de-conduire-se-fait-il-a-lannexe-ou-au-service-competent',
    topic: 'vehicule',
    questionFr: 'Le permis de conduire se fait-il à l’annexe ou au service compétent ?',
    questionAr: 'هل تتم رخصة السياقة في الملحقة أم لدى المصلحة المختصة؟',
    answerFr: 'Le permis de conduire suit plutôt la logique du réseau compétent que celle d’une annexe de quartier. Houma vous oriente vers le bon cadre.',
    answerAr: 'تتبع رخصة السياقة منطق الشبكة المختصة أكثر من منطق ملحقة الحي. وتوجهك Houma نحو الإطار الصحيح.',
    relatedServiceSlugs: ['permis-conduire'],
    relatedCitySlugs: [],
    keywords: ['permis conduire annexe', 'narsa permis conduire'],
    isGlobal: true,
    priority: 1,
  },
  'faq-carte-grise-ou-aller': {
    id: 'faq-carte-grise-ou-aller',
    slug: 'ou-aller-pour-une-carte-grise',
    topic: 'vehicule',
    questionFr: 'Où aller pour une carte grise ?',
    questionAr: 'إلى أين أتوجه بخصوص البطاقة الرمادية؟',
    answerFr: 'La carte grise relève du service compétent et des liens officiels associés. Elle ne doit pas être assimilée à une simple démarche d’annexe locale.',
    answerAr: 'تتبع البطاقة الرمادية المصلحة المختصة والروابط الرسمية المرتبطة بها. ولا ينبغي اعتبارها مجرد إجراء خاص بملحقة محلية.',
    relatedServiceSlugs: ['carte-grise'],
    relatedCitySlugs: [],
    keywords: ['carte grise ou aller', 'service carte grise'],
    isGlobal: true,
    priority: 1,
  },
  'faq-vignette-deplacement': {
    id: 'faq-vignette-deplacement',
    slug: 'la-vignette-auto-necessite-t-elle-un-deplacement',
    topic: 'fiscalite',
    questionFr: 'La vignette auto nécessite-t-elle un déplacement ?',
    questionAr: 'هل تتطلب ضريبة السيارة تنقلا؟',
    answerFr: 'En général non. La vignette auto est une démarche en ligne d’abord, avec des plateformes officielles et des preuves de paiement numériques.',
    answerAr: 'في الغالب لا. ضريبة السيارة إجراء رقمي أولا مع منصات رسمية وإثباتات أداء رقمية.',
    relatedServiceSlugs: ['vignette-auto'],
    relatedCitySlugs: [],
    keywords: ['vignette deplacement', 'vignette en ligne'],
    isGlobal: true,
    priority: 1,
  },
  'faq-carte-sejour-ou-commencer': {
    id: 'faq-carte-sejour-ou-commencer',
    slug: 'par-ou-commencer-pour-une-carte-de-sejour',
    topic: 'etrangers',
    questionFr: 'Par où commencer pour une carte de séjour ?',
    questionAr: 'من أين أبدأ طلب بطاقة الإقامة؟',
    answerFr: 'Commencez par la page du service et la procédure officielle affichée. La logique de compétence peut être différente d’une simple démarche de quartier.',
    answerAr: 'ابدأ بصفحة الخدمة وبالمسطرة الرسمية المعروضة. وقد يختلف منطق الاختصاص عن مجرد إجراء خاص بالحي.',
    relatedServiceSlugs: ['carte-sejour-etranger'],
    relatedCitySlugs: [],
    keywords: ['carte sejour commencer', 'ou aller carte sejour'],
    isGlobal: true,
    priority: 1,
  },
  'faq-permis-construire-lieu-bien': {
    id: 'faq-permis-construire-lieu-bien',
    slug: 'le-permis-de-construire-depend-il-du-lieu-du-bien',
    topic: 'urbanisme',
    questionFr: 'Le permis de construire dépend-il du lieu du bien ?',
    questionAr: 'هل تعتمد رخصة البناء على موقع العقار؟',
    answerFr: 'Oui, souvent. Pour cette démarche, le lieu du bien peut compter davantage que la simple ville ou que la proximité géographique.',
    answerAr: 'نعم غالبا. ففي هذا الإجراء قد يكون موقع العقار أهم من المدينة وحدها أو من القرب الجغرافي.',
    relatedServiceSlugs: ['permis-construire'],
    relatedCitySlugs: [],
    keywords: ['permis construire lieu du bien', 'commune permis construire'],
    isGlobal: true,
    priority: 1,
  },
  'faq-auto-entrepreneur-vs-registre-commerce': {
    id: 'faq-auto-entrepreneur-vs-registre-commerce',
    slug: 'quelle-difference-entre-auto-entrepreneur-et-registre-du-commerce',
    topic: 'entreprise',
    questionFr: 'Quelle différence entre auto-entrepreneur et registre du commerce ?',
    questionAr: 'ما الفرق بين المقاول الذاتي والسجل التجاري؟',
    answerFr: 'Ce sont deux cadres différents. Houma vous aide à choisir la bonne démarche selon votre situation avant de suivre les liens officiels adaptés.',
    answerAr: 'هما إطاران مختلفان. تساعدك Houma على اختيار الإجراء المناسب حسب وضعك قبل اتباع الروابط الرسمية الملائمة.',
    relatedServiceSlugs: ['auto-entrepreneur', 'registre-commerce'],
    relatedCitySlugs: [],
    keywords: ['auto entrepreneur registre commerce', 'difference statut'],
    isGlobal: true,
    priority: 1,
  },
  'faq-inscription-electorale-ou-aller': {
    id: 'faq-inscription-electorale-ou-aller',
    slug: 'ou-aller-pour-linscription-sur-les-listes-electorales',
    topic: 'citoyennete',
    questionFr: 'Où aller pour l’inscription sur les listes électorales ?',
    questionAr: 'إلى أين أتوجه للتسجيل في اللوائح الانتخابية؟',
    answerFr: 'Commencez par la page du service et vérifiez la logique locale ou institutionnelle affichée. La bonne ville et le bon contexte restent importants.',
    answerAr: 'ابدأ بصفحة الخدمة وتحقق من المنطق المحلي أو المؤسسي المعروض. فالمدينة الصحيحة والسياق الصحيح مهمان.',
    relatedServiceSlugs: ['inscription-liste-electorale'],
    relatedCitySlugs: [],
    keywords: ['inscription listes electorales ou aller'],
    isGlobal: true,
    priority: 1,
  },
  'faq-houma-couvre-quelles-villes': {
    id: 'faq-houma-couvre-quelles-villes',
    slug: 'houma-couvre-t-elle-dautres-villes-que-casablanca-rabat-et-tanger',
    topic: 'product',
    questionFr: 'Houma couvre-t-elle d’autres villes que Casablanca, Rabat et Tanger ?',
    questionAr: 'هل تغطي Houma مدنا أخرى غير الدار البيضاء والرباط وطنجة؟',
    answerFr: 'Pas encore. La version actuelle couvre Casablanca, Rabat et Tanger. D’autres villes peuvent être ajoutées ensuite.',
    answerAr: 'ليس بعد. النسخة الحالية تغطي الدار البيضاء والرباط وطنجة. ويمكن إضافة مدن أخرى لاحقا.',
    relatedServiceSlugs: [],
    relatedCitySlugs: [],
    keywords: ['Houma villes couvertes', 'villes supportees'],
    isGlobal: true,
    priority: 1,
  },
  'faq-houma-preuve-officielle': {
    id: 'faq-houma-preuve-officielle',
    slug: 'puis-je-utiliser-houma-comme-preuve-officielle',
    topic: 'product',
    questionFr: 'Puis-je utiliser Houma comme preuve officielle ?',
    questionAr: 'هل يمكنني استعمال Houma كإثبات رسمي؟',
    answerFr: 'Non. Houma est un site d’information qui aide à comprendre les documents, les étapes et l’autorité locale concernée. Les sources officielles et les administrations compétentes restent la référence.',
    answerAr: 'لا. Houma موقع معلوماتي يساعد على فهم الوثائق والخطوات والسلطة المحلية المعنية. وتبقى المصادر الرسمية والإدارات المختصة هي المرجع.',
    relatedServiceSlugs: [],
    relatedCitySlugs: [],
    keywords: ['Houma preuve officielle', 'guide non officiel'],
    isGlobal: true,
    priority: 1,
  },
}
