import type { GuideCategory, GuideRecord } from '@/types/models'

export const guideCategories: GuideCategory[] = [
  'identite',
  'attestations',
  'etat-civil',
  'justice',
  'vehicule',
  'fiscalite',
  'etrangers',
  'entreprise',
  'urbanisme',
  'citoyennete',
]

export const guideOrder = [
  'passeport-et-cnie-dans-les-villes-couvertes',
  'attestation-residence-et-legalisation-ou-aller',
  'actes-familiaux-naissance-deces-livret',
  'casier-judiciaire-demarche-et-delais',
  'permis-conduire-et-carte-grise-bon-guichet',
  'vignette-auto-paiement-et-exoneration',
  'carte-sejour-pour-etrangers-ou-commencer',
  'auto-entrepreneur-et-registre-commerce',
  'permis-de-construire-et-demarches-communales',
  'inscription-electorale-et-preparation-avant-deplacement',
] as const

export const featuredGuideSlugs = [
  'passeport-et-cnie-dans-les-villes-couvertes',
  'attestation-residence-et-legalisation-ou-aller',
  'vignette-auto-paiement-et-exoneration',
  'inscription-electorale-et-preparation-avant-deplacement',
] as const

export const guides: Record<string, GuideRecord> = {
  'passeport-et-cnie-dans-les-villes-couvertes': {
    slug: 'passeport-et-cnie-dans-les-villes-couvertes',
    category: 'identite',
    titleFr: 'Passeport et CNIE dans les villes couvertes',
    titleAr: 'جواز السفر والبطاقة الوطنية في المدن المغطاة',
    descriptionFr: 'Comprendre où déposer un dossier de passeport, de renouvellement CNIE ou de duplicata CIN selon la ville et la zone.',
    descriptionAr: 'فهم مكان إيداع ملف جواز السفر أو تجديد البطاقة الوطنية أو نظير البطاقة حسب المدينة والمنطقة.',
    introFr: 'Pour les démarches d’identité, la ville donne souvent un bon point de départ, mais la zone peut affiner l’autorité responsable. Houma affiche la zone comme contexte et l’autorité responsable comme réponse finale.',
    introAr: 'في إجراءات الهوية تعطي المدينة غالبا نقطة انطلاق جيدة، لكن المنطقة قد تجعل الجواب أدق. تعرض Houma المنطقة كسياق والجهة المسؤولة كجواب نهائي.',
    sections: [
      {
        headingFr: 'Quand la ville suffit',
        headingAr: 'متى تكفي المدينة',
        bodyFr: 'Certaines réponses peuvent être affichées au niveau ville lorsque la zone n’est pas encore confirmée. Cela évite de bloquer le parcours tout en gardant une logique réaliste.',
        bodyAr: 'يمكن عرض بعض الأجوبة على مستوى المدينة عندما لا تكون المنطقة مؤكدة بعد. هذا يمنع تعطيل المسار مع الحفاظ على منطق واقعي.',
      },
      {
        headingFr: 'Quand la zone améliore la réponse',
        headingAr: 'متى تجعل المنطقة الجواب أدق',
        bodyFr: 'Pour un passeport, un renouvellement CNIE ou un duplicata CIN, la zone sélectionnée aide à rapprocher la réponse de votre autorité locale de référence.',
        bodyAr: 'في جواز السفر أو تجديد البطاقة الوطنية أو نظير البطاقة تساعد المنطقة المختارة على تقريب الجواب من جهتك المحلية المرجعية.',
      },
      {
        headingFr: 'Pièces, frais et erreurs fréquentes',
        headingAr: 'الوثائق والرسوم والأخطاء الشائعة',
        bodyFr: 'Avant de vous déplacer, vérifiez toujours les pièces, les frais et le lien officiel affichés sur la page du service concerné.',
        bodyAr: 'قبل التنقل تحقق دائما من الوثائق والرسوم والرابط الرسمي المعروض في صفحة الخدمة المعنية.',
      },
    ],
    relatedServiceSlugs: ['passeport-marocain', 'renouvellement-cnie', 'duplicata-cin'],
    relatedCitySlugs: [],
    faqIds: ['faq-passeport-annexe-responsable', 'faq-passeport-nimporte-quelle-annexe', 'faq-renouvellement-cnie-ou-aller', 'faq-duplicata-cin-ou-aller', 'faq-zone-vs-autorite'],
    seoTitleFr: 'Passeport, CNIE et duplicata CIN dans les villes couvertes | Houma',
    seoTitleAr: 'جواز السفر والبطاقة الوطنية ونظير البطاقة في المدن المغطاة | Houma',
    seoDescriptionFr: 'Guide pratique pour comprendre la ville, la zone sélectionnée et l’autorité responsable pour les démarches d’identité.',
    seoDescriptionAr: 'دليل عملي لفهم المدينة والمنطقة المختارة والجهة المسؤولة في إجراءات الهوية.',
    featured: true,
    isEvergreen: true,
    futureCityReady: true,
  },
  'attestation-residence-et-legalisation-ou-aller': {
    slug: 'attestation-residence-et-legalisation-ou-aller',
    category: 'attestations',
    titleFr: 'Attestation de résidence et légalisation : où aller',
    titleAr: 'شهادة السكنى والمصادقة: إلى أين أتوجه',
    descriptionFr: 'Choisir le bon guichet pour une attestation de résidence ou une légalisation de signature selon votre lieu de résidence.',
    descriptionAr: 'اختيار الشباك المناسب لشهادة السكنى أو المصادقة على الإمضاء حسب مكان السكن.',
    introFr: 'Ces démarches dépendent souvent de la compétence locale. Houma peut afficher une réponse au niveau ville, mais la zone peut améliorer la précision.',
    introAr: 'هذه الإجراءات تعتمد غالبا على الاختصاص المحلي. يمكن لـ Houma أن تعرض جوابا على مستوى المدينة، لكن المنطقة قد تجعل الجواب أدق.',
    sections: [
      {
        headingFr: 'Zone sélectionnée et compétence locale',
        headingAr: 'المنطقة المختارة والاختصاص المحلي',
        bodyFr: 'L’attestation de résidence et la légalisation de signature relèvent souvent de la logique locale. La zone aide à trouver la bonne autorité plutôt que le bureau le plus proche.',
        bodyAr: 'شهادة السكنى والمصادقة على الإمضاء تخضعان غالبا لمنطق محلي. تساعد المنطقة على إيجاد الجهة الصحيحة بدل البحث عن أقرب مكتب.',
      },
      {
        headingFr: 'Documents utiles et délais',
        headingAr: 'الوثائق المفيدة والآجال',
        bodyFr: 'Préparez une pièce d’identité valide, un justificatif de domicile récent et tout document original à signer ou à faire légaliser.',
        bodyAr: 'أعد وثيقة هوية سارية وإثبات سكن حديث وكل وثيقة أصلية ستوقع أو ستصادق عليها.',
      },
      {
        headingFr: 'Quand vérifier une source officielle',
        headingAr: 'متى يجب الرجوع إلى مصدر رسمي',
        bodyFr: 'Si une administration applique une règle locale particulière, la source officielle ou l’information reçue au guichet reste prioritaire sur le résumé éditorial.',
        bodyAr: 'إذا طبقت إدارة قاعدة محلية خاصة، يبقى المصدر الرسمي أو ما يقدم لك في الشباك أولى من الملخص التحريري.',
      },
    ],
    relatedServiceSlugs: ['attestation-residence', 'legalisation-signature'],
    relatedCitySlugs: [],
    faqIds: ['faq-documents-attestation-residence', 'faq-attestation-meme-jour', 'faq-legalisation-sans-rendez-vous', 'faq-legalisation-vs-copie-conforme', 'faq-bureau-pas-forcement-plus-proche'],
    seoTitleFr: 'Attestation de résidence et légalisation : où aller | Houma',
    seoTitleAr: 'شهادة السكنى والمصادقة: إلى أين أتوجه | Houma',
    seoDescriptionFr: 'Comprendre quelle autorité locale peut être compétente pour l’attestation de résidence et la légalisation.',
    seoDescriptionAr: 'فهم أي جهة محلية قد تكون مختصة في شهادة السكنى والمصادقة.',
    featured: true,
    isEvergreen: true,
    futureCityReady: true,
  },
  'actes-familiaux-naissance-deces-livret': {
    slug: 'actes-familiaux-naissance-deces-livret',
    category: 'etat-civil',
    titleFr: 'Actes familiaux : naissance, décès, livret',
    titleAr: 'وثائق الحالة المدنية: الولادة والوفاة والدفتر العائلي',
    descriptionFr: 'Comprendre quand utiliser Watiqa, quand aller à l’état civil et quelles pièces préparer pour les actes familiaux.',
    descriptionAr: 'فهم متى تستخدم وثيقة ومتى تتوجه إلى الحالة المدنية وما الوثائق التي يجب إعدادها للوثائق العائلية.',
    introFr: 'Les actes familiaux ne suivent pas tous la même logique. Certains cas se prêtent au parcours en ligne, d’autres demandent encore un passage au bureau d’état civil.',
    introAr: 'الوثائق العائلية لا تتبع كلها المنطق نفسه. فبعض الحالات تناسب المسار الرقمي، وبعضها ما زال يتطلب المرور إلى مكتب الحالة المدنية.',
    sections: [
      {
        headingFr: 'Naissance : en ligne ou au guichet',
        headingAr: 'الولادة: عبر الإنترنت أم في الشباك',
        bodyFr: 'Watiqa peut être utile pour certaines demandes d’acte de naissance, mais elle ne couvre pas toutes les situations. Le lieu d’état civil reste central.',
        bodyAr: 'قد تكون وثيقة مفيدة في بعض طلبات عقد الازدياد، لكنها لا تغطي كل الحالات. ويظل مكان الحالة المدنية عنصرا أساسيا.',
      },
      {
        headingFr: 'Livret de famille et acte de décès',
        headingAr: 'الدفتر العائلي وعقد الوفاة',
        bodyFr: 'Le livret de famille et l’acte de décès peuvent dépendre de pièces spécifiques, du contexte familial et parfois de la commune ou du bureau d’état civil concerné.',
        bodyAr: 'قد يعتمد الدفتر العائلي وعقد الوفاة على وثائق خاصة وعلى السياق العائلي وأحيانا على الجماعة أو مكتب الحالة المدنية المعني.',
      },
      {
        headingFr: 'Quand une autre ville compte',
        headingAr: 'متى تصبح مدينة أخرى مهمة',
        bodyFr: 'Le lieu d’origine de l’acte peut compter davantage que votre ville actuelle. C’est pour cela que Houma ne transforme pas systématiquement une recherche locale en certitude.',
        bodyAr: 'قد يكون مكان أصل الوثيقة أهم من مدينتك الحالية. ولهذا لا تحول Houma كل بحث محلي إلى يقين نهائي.',
      },
    ],
    relatedServiceSlugs: ['acte-naissance', 'livret-famille', 'acte-deces'],
    relatedCitySlugs: [],
    faqIds: ['faq-acte-naissance-autre-ville', 'faq-watiqa-remplace-guichet', 'faq-livret-famille-ou-aller', 'faq-acte-deces-quelle-administration'],
    seoTitleFr: 'Actes familiaux : naissance, décès, livret | Houma',
    seoTitleAr: 'وثائق الحالة المدنية: الولادة والوفاة والدفتر العائلي | Houma',
    seoDescriptionFr: 'Guide pratique pour comprendre Watiqa, l’état civil et les pièces utiles pour les actes familiaux.',
    seoDescriptionAr: 'دليل عملي لفهم وثيقة والحالة المدنية والوثائق المفيدة للوثائق العائلية.',
    isEvergreen: true,
    futureCityReady: true,
  },
  'casier-judiciaire-demarche-et-delais': {
    slug: 'casier-judiciaire-demarche-et-delais',
    category: 'justice',
    titleFr: 'Casier judiciaire : démarche, pièces et délais',
    titleAr: 'السجل العدلي: المسطرة والوثائق والآجال',
    descriptionFr: 'Préparer une demande de casier judiciaire, comprendre la part en ligne et savoir quoi vérifier avant de se déplacer.',
    descriptionAr: 'إعداد طلب السجل العدلي وفهم الجزء الإلكتروني ومعرفة ما يجب التحقق منه قبل التنقل.',
    introFr: 'Le casier judiciaire ne suit pas la même logique que les annexes locales. Le plus important est d’utiliser la bonne procédure et le bon lien officiel.',
    introAr: 'السجل العدلي لا يتبع المنطق نفسه الخاص بالملحقات المحلية. الأهم هو استعمال المسطرة الصحيحة والرابط الرسمي الصحيح.',
    sections: [
      {
        headingFr: 'Une démarche différente des annexes',
        headingAr: 'إجراء مختلف عن الملحقات',
        bodyFr: 'Le casier judiciaire dépend d’une logique judiciaire et institutionnelle. Il ne faut pas le lire comme un simple service de quartier.',
        bodyAr: 'يعتمد السجل العدلي على منطق قضائي ومؤسساتي. ولا ينبغي اعتباره مجرد خدمة حي.',
      },
      {
        headingFr: 'Part en ligne et retrait',
        headingAr: 'الجزء الرقمي والاستلام',
        bodyFr: 'Une partie du parcours peut être en ligne, selon la procédure officielle. La page de service doit rester votre point de repère pour les liens et étapes.',
        bodyAr: 'قد يكون جزء من المسار رقميا حسب المسطرة الرسمية. ويجب أن تبقى صفحة الخدمة هي مرجعك للروابط والخطوات.',
      },
      {
        headingFr: 'Pièces et délais',
        headingAr: 'الوثائق والآجال',
        bodyFr: 'Préparez les pièces demandées et vérifiez les délais les plus récents. Les pratiques peuvent évoluer.',
        bodyAr: 'أعد الوثائق المطلوبة وتحقق من أحدث الآجال. فقد تتغير الممارسة.',
      },
    ],
    relatedServiceSlugs: ['casier-judiciaire'],
    relatedCitySlugs: [],
    faqIds: ['faq-casier-en-ligne'],
    seoTitleFr: 'Casier judiciaire : pièces, démarche et délais | Houma',
    seoTitleAr: 'السجل العدلي: الوثائق والمسار والآجال | Houma',
    seoDescriptionFr: 'Comprendre la demande de casier judiciaire sans la confondre avec une démarche d’annexe locale.',
    seoDescriptionAr: 'فهم طلب السجل العدلي دون الخلط بينه وبين إجراء تابع لملحقة محلية.',
    isEvergreen: true,
    futureCityReady: true,
  },
  'permis-conduire-et-carte-grise-bon-guichet': {
    slug: 'permis-conduire-et-carte-grise-bon-guichet',
    category: 'vehicule',
    titleFr: 'Permis de conduire et carte grise : le bon guichet',
    titleAr: 'رخصة السياقة والبطاقة الرمادية: الشباك المناسب',
    descriptionFr: 'Savoir quels services relèvent de NARSA, quels liens officiels utiliser et quand un repère ville suffit.',
    descriptionAr: 'معرفة أي الخدمات تابعة لـ NARSA وأي الروابط الرسمية يجب استعمالها ومتى تكفي المدينة فقط.',
    introFr: 'Pour les démarches véhicule, la bonne question n’est pas seulement où aller, mais aussi quel réseau officiel utiliser.',
    introAr: 'في إجراءات المركبات ليس السؤال الصحيح فقط هو إلى أين أذهب، بل أيضا ما الشبكة الرسمية التي يجب استعمالها.',
    sections: [
      {
        headingFr: 'Des démarches souvent citywide',
        headingAr: 'إجراءات غالبا على مستوى المدينة',
        bodyFr: 'Le permis de conduire et la carte grise relèvent souvent d’un traitement à l’échelle de la ville ou du réseau compétent, sans logique d’annexe de quartier.',
        bodyAr: 'رخصة السياقة والبطاقة الرمادية تخضعان غالبا لمعالجة على مستوى المدينة أو الشبكة المختصة، لا لمنطق ملحقة الحي.',
      },
      {
        headingFr: 'Vérifier le bon lien officiel',
        headingAr: 'التحقق من الرابط الرسمي الصحيح',
        bodyFr: 'Avant tout déplacement, ouvrez le lien officiel affiché par Houma pour vérifier les documents, frais ou services numériques associés.',
        bodyAr: 'قبل أي تنقل افتح الرابط الرسمي الذي تعرضه Houma للتحقق من الوثائق والرسوم أو الخدمات الرقمية المرتبطة.',
      },
      {
        headingFr: 'Cas fréquents',
        headingAr: 'الحالات الشائعة',
        bodyFr: 'Renouvellement, duplicata, retrait ou mise à jour ne suivent pas toujours exactement le même parcours.',
        bodyAr: 'التجديد أو النظير أو السحب أو التحيين لا يتبع دائما المسار نفسه تماما.',
      },
    ],
    relatedServiceSlugs: ['permis-conduire', 'carte-grise'],
    relatedCitySlugs: [],
    faqIds: ['faq-permis-ville-ou-annexe', 'faq-carte-grise-ou-aller'],
    seoTitleFr: 'Permis de conduire et carte grise : le bon guichet | Houma',
    seoTitleAr: 'رخصة السياقة والبطاقة الرمادية: الشباك المناسب | Houma',
    seoDescriptionFr: 'Guide pour distinguer les démarches véhicule citywide des démarches locales de quartier.',
    seoDescriptionAr: 'دليل لتمييز إجراءات المركبات على مستوى المدينة عن الإجراءات المحلية الخاصة بالأحياء.',
    isEvergreen: true,
    futureCityReady: true,
  },
  'vignette-auto-paiement-et-exoneration': {
    slug: 'vignette-auto-paiement-et-exoneration',
    category: 'fiscalite',
    titleFr: 'Vignette auto : paiement, preuve et exonération',
    titleAr: 'ضريبة السيارة: الأداء والإثبات والإعفاء',
    descriptionFr: 'Expliquer le parcours en ligne, les justificatifs utiles et les cas d’exonération sans faire croire à une démarche d’annexe.',
    descriptionAr: 'شرح المسار عبر الإنترنت والمستندات المفيدة وحالات الإعفاء دون الإيحاء بأنها معاملة ملحقة.',
    introFr: 'La vignette auto est un bon exemple de démarche en ligne d’abord. Même dans un produit local, elle ne doit pas être présentée comme un service d’annexe.',
    introAr: 'ضريبة السيارة مثال واضح على إجراء رقمي أولا. وحتى داخل منتج محلي لا ينبغي تقديمها كخدمة ملحقة.',
    sections: [
      {
        headingFr: 'Une démarche en ligne avant tout',
        headingAr: 'إجراء رقمي قبل كل شيء',
        bodyFr: 'La page doit orienter vers le paiement officiel en ligne, les preuves utiles et les notes d’exonération éventuelles.',
        bodyAr: 'يجب أن توجه الصفحة نحو الأداء الرسمي عبر الإنترنت وإثباتات الأداء المفيدة وملاحظات الإعفاء عند الاقتضاء.',
      },
      {
        headingFr: 'Preuve de paiement et justificatifs',
        headingAr: 'إثبات الأداء والمستندات',
        bodyFr: 'Conservez la preuve de paiement et vérifiez les instructions de téléchargement ou d’impression indiquées par la source officielle.',
        bodyAr: 'احتفظ بإثبات الأداء وتحقق من تعليمات التحميل أو الطباعة التي يشير إليها المصدر الرسمي.',
      },
      {
        headingFr: 'Exonération et limites',
        headingAr: 'الإعفاء والحدود',
        bodyFr: 'Les cas d’exonération doivent toujours rester rattachés à une source officielle. Le produit ne doit pas transformer une règle fiscale en simple rumeur locale.',
        bodyAr: 'يجب أن تبقى حالات الإعفاء مرتبطة دائما بمصدر رسمي. ولا ينبغي أن يحول المنتج قاعدة ضريبية إلى مجرد معلومة محلية متداولة.',
      },
    ],
    relatedServiceSlugs: ['vignette-auto'],
    relatedCitySlugs: [],
    faqIds: ['faq-vignette-deplacement'],
    seoTitleFr: 'Vignette auto : paiement, preuve et exonération | Houma',
    seoTitleAr: 'ضريبة السيارة: الأداء والإثبات والإعفاء | Houma',
    seoDescriptionFr: 'Guide sur la vignette auto, le paiement en ligne, la preuve de paiement et les cas d’exonération.',
    seoDescriptionAr: 'دليل حول ضريبة السيارة والأداء عبر الإنترنت وإثبات الأداء وحالات الإعفاء.',
    featured: true,
    isEvergreen: true,
    futureCityReady: true,
  },
  'carte-sejour-pour-etrangers-ou-commencer': {
    slug: 'carte-sejour-pour-etrangers-ou-commencer',
    category: 'etrangers',
    titleFr: 'Carte de séjour pour étrangers : où commencer',
    titleAr: 'بطاقة الإقامة للأجانب: من أين أبدأ',
    descriptionFr: 'Repères pour préparer une demande de carte de séjour, distinguer le service compétent et vérifier les pièces avant déplacement.',
    descriptionAr: 'مؤشرات لإعداد طلب بطاقة الإقامة وتمييز الجهة المختصة والتحقق من الوثائق قبل التنقل.',
    introFr: 'La carte de séjour obéit à sa propre logique administrative. La page du service doit aider à commencer correctement, sans simplifier à l’excès.',
    introAr: 'تخضع بطاقة الإقامة لمنطق إداري خاص بها. ويجب أن تساعد صفحة الخدمة على البداية الصحيحة دون تبسيط مخل.',
    sections: [
      {
        headingFr: 'Par où commencer',
        headingAr: 'من أين أبدأ',
        bodyFr: 'Commencez par les pièces de base et par la procédure officielle affichée. N’assimilez pas cette démarche à une simple annexe de quartier.',
        bodyAr: 'ابدأ بالوثائق الأساسية وبالمسطرة الرسمية المعروضة. ولا تعتبر هذا الإجراء مجرد ملحقة حي.',
      },
      {
        headingFr: 'Ville et autorité compétente',
        headingAr: 'المدينة والجهة المختصة',
        bodyFr: 'La ville sert souvent de repère. L’autorité réellement compétente dépend ensuite de la nature exacte du dossier.',
        bodyAr: 'تستعمل المدينة غالبا كمرجع. ثم تتحدد الجهة المختصة فعلا حسب طبيعة الملف الدقيقة.',
      },
      {
        headingFr: 'Quand vérifier directement',
        headingAr: 'متى يجب التحقق مباشرة',
        bodyFr: 'Si votre situation est particulière, la source officielle et le service compétent doivent primer sur tout résumé éditorial.',
        bodyAr: 'إذا كانت وضعيتك خاصة، فيجب أن يتقدم المصدر الرسمي والخدمة المختصة على أي ملخص تحريري.',
      },
    ],
    relatedServiceSlugs: ['carte-sejour-etranger'],
    relatedCitySlugs: [],
    faqIds: ['faq-carte-sejour-ou-commencer'],
    seoTitleFr: 'Carte de séjour pour étrangers : où commencer | Houma',
    seoTitleAr: 'بطاقة الإقامة للأجانب: من أين أبدأ | Houma',
    seoDescriptionFr: 'Guide pratique pour préparer une demande de carte de séjour sans confondre la logique de compétence.',
    seoDescriptionAr: 'دليل عملي لإعداد طلب بطاقة الإقامة دون الخلط في منطق الاختصاص.',
    isEvergreen: true,
    futureCityReady: true,
  },
  'auto-entrepreneur-et-registre-commerce': {
    slug: 'auto-entrepreneur-et-registre-commerce',
    category: 'entreprise',
    titleFr: 'Auto-entrepreneur et registre du commerce',
    titleAr: 'المقاول الذاتي والسجل التجاري',
    descriptionFr: 'Comparer deux démarches souvent confondues, avec les bons liens officiels et les étapes de préparation.',
    descriptionAr: 'مقارنة بين إجراءين غالبا ما يتم الخلط بينهما مع الروابط الرسمية الصحيحة وخطوات التحضير.',
    introFr: 'Beaucoup d’utilisateurs hésitent entre auto-entrepreneur et registre du commerce. Un bon guide doit clarifier le choix avant même l’ouverture d’une page de service.',
    introAr: 'يتردد كثير من المستخدمين بين المقاول الذاتي والسجل التجاري. ويجب أن يوضح الدليل الجيد الاختيار قبل حتى فتح صفحة خدمة.',
    sections: [
      {
        headingFr: 'Deux cadres différents',
        headingAr: 'إطاران مختلفان',
        bodyFr: 'L’auto-entrepreneur et le registre du commerce ne répondent pas aux mêmes besoins. Le choix change les pièces, les frais et parfois le réseau compétent.',
        bodyAr: 'المقاول الذاتي والسجل التجاري لا يجيبان عن الحاجات نفسها. ويغير الاختيار الوثائق والرسوم وأحيانا الشبكة المختصة.',
      },
      {
        headingFr: 'Documents et préparation',
        headingAr: 'الوثائق والتحضير',
        bodyFr: 'Avant de lancer une démarche, lisez les conditions officielles et préparez les justificatifs les plus courants.',
        bodyAr: 'قبل بدء أي إجراء اقرأ الشروط الرسمية وأعد المستندات الأكثر شيوعا.',
      },
      {
        headingFr: 'Ville, greffe et portail',
        headingAr: 'المدينة وكتابة الضبط والبوابة',
        bodyFr: 'Selon le cadre choisi, la logique peut être nationale, portail d’inscription ou juridiction commerciale compétente.',
        bodyAr: 'حسب الإطار المختار قد يكون المنطق وطنيا أو مرتبطا ببوابة تسجيل أو بجهة تجارية مختصة.',
      },
    ],
    relatedServiceSlugs: ['auto-entrepreneur', 'registre-commerce'],
    relatedCitySlugs: [],
    faqIds: ['faq-auto-entrepreneur-vs-registre-commerce'],
    seoTitleFr: 'Auto-entrepreneur et registre du commerce | Houma',
    seoTitleAr: 'المقاول الذاتي والسجل التجاري | Houma',
    seoDescriptionFr: 'Comparer auto-entrepreneur et registre du commerce avant de lancer la bonne démarche.',
    seoDescriptionAr: 'مقارنة المقاول الذاتي والسجل التجاري قبل بدء الإجراء المناسب.',
    isEvergreen: true,
    futureCityReady: true,
  },
  'permis-de-construire-et-demarches-communales': {
    slug: 'permis-de-construire-et-demarches-communales',
    category: 'urbanisme',
    titleFr: 'Permis de construire et démarches communales',
    titleAr: 'رخصة البناء والإجراءات الجماعية',
    descriptionFr: 'Comprendre les démarches communales qui dépendent du lieu du bien et non seulement de la ville.',
    descriptionAr: 'فهم الإجراءات الجماعية التي تعتمد على موقع العقار وليس على المدينة فقط.',
    introFr: 'Le permis de construire montre bien pourquoi la proximité ne suffit pas. Le lieu du bien et la compétence locale comptent davantage.',
    introAr: 'توضح رخصة البناء جيدا لماذا لا يكفي القرب. فموقع العقار والاختصاص المحلي أهم من ذلك.',
    sections: [
      {
        headingFr: 'Le lieu du bien avant tout',
        headingAr: 'موقع العقار أولا',
        bodyFr: 'La compétence peut dépendre de la commune, du ressort ou d’une organisation locale précise liée au lieu du bien.',
        bodyAr: 'قد يرتبط الاختصاص بالجماعة أو بالمجال الترابي أو بتنظيم محلي محدد مرتبط بموقع العقار.',
      },
      {
        headingFr: 'Pièces techniques',
        headingAr: 'الوثائق التقنية',
        bodyFr: 'Ce type de démarche demande souvent des pièces techniques et des validations qui dépassent un simple guichet d’accueil.',
        bodyAr: 'يتطلب هذا النوع من الإجراءات غالبا وثائق تقنية وموافقات تتجاوز مجرد شباك استقبال.',
      },
      {
        headingFr: 'Pourquoi la zone compte',
        headingAr: 'لماذا تهم المنطقة',
        bodyFr: 'Ici, la zone ne sert pas à personnaliser un détail cosmétique. Elle peut changer l’autorité réellement compétente.',
        bodyAr: 'هنا لا تستعمل المنطقة لتخصيص شكلي فقط. بل قد تغير الجهة المختصة فعلا.',
      },
    ],
    relatedServiceSlugs: ['permis-construire'],
    relatedCitySlugs: [],
    faqIds: ['faq-permis-construire-lieu-bien'],
    seoTitleFr: 'Permis de construire et démarches communales | Houma',
    seoTitleAr: 'رخصة البناء والإجراءات الجماعية | Houma',
    seoDescriptionFr: 'Guide pour comprendre le rôle du lieu du bien, de la commune et de la compétence locale.',
    seoDescriptionAr: 'دليل لفهم دور موقع العقار والجماعة والاختصاص المحلي.',
    isEvergreen: true,
    futureCityReady: true,
  },
  'inscription-electorale-et-preparation-avant-deplacement': {
    slug: 'inscription-electorale-et-preparation-avant-deplacement',
    category: 'citoyennete',
    titleFr: 'Inscription électorale et préparation avant déplacement',
    titleAr: 'التسجيل الانتخابي والتحضير قبل التنقل',
    descriptionFr: 'Préparer un déplacement administratif utile, comprendre l’inscription électorale et éviter les erreurs de guichet.',
    descriptionAr: 'التحضير لتنقل إداري مفيد وفهم التسجيل الانتخابي وتجنب أخطاء الشباك.',
    introFr: 'Ce guide transversal aide à mieux utiliser Houma avant de se déplacer, y compris pour l’inscription électorale et les démarches qui changent selon la zone.',
    introAr: 'يساعد هذا الدليل العرضي على استعمال Houma بشكل أفضل قبل التنقل، بما في ذلك التسجيل الانتخابي والإجراءات التي تتغير حسب المنطقة.',
    sections: [
      {
        headingFr: 'Inscription électorale',
        headingAr: 'التسجيل الانتخابي',
        bodyFr: 'L’inscription électorale dépend de règles spécifiques. La bonne ville et, parfois, le bon contexte local comptent.',
        bodyAr: 'يخضع التسجيل الانتخابي لقواعد خاصة. فالمدينة الصحيحة وأحيانا السياق المحلي الصحيح مهمان.',
      },
      {
        headingFr: 'Avant de se déplacer',
        headingAr: 'قبل التنقل',
        bodyFr: 'Vérifiez les pièces, le coût éventuel, la logique locale et le lien officiel. Ce simple réflexe évite beaucoup d’aller-retours.',
        bodyAr: 'تحقق من الوثائق والكلفة المحتملة والمنطق المحلي والرابط الرسمي. فهذا السلوك البسيط يجنب كثيرا من الذهاب والإياب.',
      },
      {
        headingFr: 'Quand ajouter une zone',
        headingAr: 'متى تضيف منطقة',
        bodyFr: 'Ajoutez une zone surtout lorsque la page indique qu’une réponse plus précise dépend de votre contexte local.',
        bodyAr: 'أضف منطقة خصوصا عندما تشير الصفحة إلى أن الجواب الأدق يعتمد على سياقك المحلي.',
      },
    ],
    relatedServiceSlugs: ['inscription-liste-electorale', 'passeport-marocain', 'attestation-residence', 'legalisation-signature'],
    relatedCitySlugs: [],
    faqIds: ['faq-que-faire-si-zone-non-detectee', 'faq-inscription-electorale-ou-aller', 'faq-houma-couvre-quelles-villes'],
    seoTitleFr: 'Inscription électorale et préparation avant déplacement | Houma',
    seoTitleAr: 'التسجيل الانتخابي والتحضير قبل التنقل | Houma',
    seoDescriptionFr: 'Guide transversal pour préparer une démarche locale, vérifier les sources et éviter un déplacement inutile.',
    seoDescriptionAr: 'دليل عرضي للتحضير لإجراء محلي والتحقق من المصادر وتجنب تنقل غير ضروري.',
    featured: true,
    isEvergreen: true,
    futureCityReady: true,
  },
}
