import type { SourceRecord } from '@/types/models'

export const sources: Record<string, SourceRecord> = {
  passeport: {
    slug: 'passeport',
    label: 'passeport.ma',
    domain: 'passeport.ma',
    sourceType: 'official_portal',
    url: 'https://passeport.ma',
    lastReviewedAt: '2026-03-27',
    serviceSlugs: ['passeport-marocain'],
    notesFr: 'Portail officiel utilisé pour le formulaire et la liste des pièces du passeport marocain.',
    notesAr: 'البوابة الرسمية المستعملة لاستمارة ولائحة وثائق جواز السفر المغربي.',
  },
  dgsn: {
    slug: 'dgsn',
    label: 'dgsn.ma',
    domain: 'www.dgsn.ma',
    sourceType: 'ministry',
    url: 'https://www.dgsn.ma',
    lastReviewedAt: '2026-03-27',
    serviceSlugs: ['renouvellement-cnie', 'duplicata-cin'],
    notesFr: 'Référence officielle DGSN pour les démarches d’identité.',
    notesAr: 'مرجع رسمي للمديرية العامة للأمن الوطني لمساطر الهوية.',
  },
  idarati: {
    slug: 'idarati',
    label: 'idarati.ma',
    domain: 'www.idarati.ma',
    sourceType: 'official_portal',
    url: 'https://www.idarati.ma',
    lastReviewedAt: '2026-03-27',
    serviceSlugs: [
      'renouvellement-cnie',
      'livret-famille',
      'acte-deces',
      'permis-conduire',
      'duplicata-cin',
      'carte-grise',
      'carte-sejour-etranger',
      'permis-construire',
      'auto-entrepreneur',
      'registre-commerce',
      'inscription-liste-electorale',
    ],
    notesFr: "Portail national des procédures administratives utilisé pour les pièces, frais et délais officiels.",
    notesAr: 'البوابة الوطنية للمساطر الإدارية المعتمدة للوثائق والرسوم والآجال الرسمية.',
  },
  portail: {
    slug: 'portail',
    label: 'portail.ma',
    domain: 'www.portail.ma',
    sourceType: 'official_portal',
    url: 'https://www.portail.ma',
    lastReviewedAt: '2026-03-27',
    serviceSlugs: ['attestation-residence', 'legalisation-signature'],
    notesFr: 'Portail national utilisé pour les procédures communales générales.',
    notesAr: 'البوابة الوطنية المعتمدة للمساطر الجماعية العامة.',
  },
  watiqa: {
    slug: 'watiqa',
    label: 'watiqa.ma',
    domain: 'watiqa.ma',
    sourceType: 'official_portal',
    url: 'https://watiqa.ma',
    lastReviewedAt: '2026-03-27',
    serviceSlugs: ['acte-naissance'],
    notesFr: 'Service officiel de demande en ligne des actes d’état civil.',
    notesAr: 'الخدمة الرسمية لطلب وثائق الحالة المدنية عبر الإنترنت.',
  },
  'justice-casier': {
    slug: 'justice-casier',
    label: 'casierjudiciaire.justice.gov.ma',
    domain: 'casierjudiciaire.justice.gov.ma',
    sourceType: 'ministry',
    url: 'https://casierjudiciaire.justice.gov.ma',
    lastReviewedAt: '2026-03-27',
    serviceSlugs: ['casier-judiciaire'],
    notesFr: 'Service officiel du ministère de la Justice pour le bulletin n°3.',
    notesAr: 'الخدمة الرسمية لوزارة العدل الخاصة بالبطاقة رقم 3.',
  },
  tax: {
    slug: 'tax',
    label: 'tax.gov.ma',
    domain: 'www.tax.gov.ma',
    sourceType: 'tax_authority',
    url: 'https://www.tax.gov.ma',
    lastReviewedAt: '2026-03-28',
    serviceSlugs: ['vignette-auto'],
    notesFr: 'Référence DGI pour la TSAVA et ses exonérations.',
    notesAr: 'مرجع المديرية العامة للضرائب للرسم السنوي على المركبات والإعفاءات.',
  },
  etimfisc: {
    slug: 'etimfisc',
    label: 'etf.tax.gov.ma/etimfisc',
    domain: 'etf.tax.gov.ma',
    sourceType: 'tax_authority',
    url: 'https://etf.tax.gov.ma/etimfisc',
    lastReviewedAt: '2026-03-27',
    serviceSlugs: ['passeport-marocain', 'renouvellement-cnie'],
    notesFr: 'Portail officiel du e-timbre pour les droits fiscaux applicables.',
    notesAr: 'البوابة الرسمية للطابع الجبائي الإلكتروني لأداء الرسوم الجبائية.',
  },
  'casablanca-city': {
    slug: 'casablanca-city',
    label: 'casablancacity.ma',
    domain: 'www.casablancacity.ma',
    sourceType: 'city_portal',
    url: 'https://www.casablancacity.ma',
    lastReviewedAt: '2026-03-27',
    serviceSlugs: [],
    notesFr: 'Portail institutionnel de la commune de Casablanca.',
    notesAr: 'البوابة المؤسساتية لجماعة الدار البيضاء.',
  },
  'rabat-city': {
    slug: 'rabat-city',
    label: 'mairie.rabat.ma',
    domain: 'www.mairie.rabat.ma',
    sourceType: 'city_portal',
    url: 'https://www.mairie.rabat.ma',
    lastReviewedAt: '2026-03-27',
    serviceSlugs: [],
    notesFr: 'Portail institutionnel de la commune de Rabat.',
    notesAr: 'البوابة المؤسساتية لجماعة الرباط.',
  },
  'tanger-city': {
    slug: 'tanger-city',
    label: 'tanger.ma',
    domain: 'www.tanger.ma',
    sourceType: 'city_portal',
    url: 'https://www.tanger.ma',
    lastReviewedAt: '2026-03-27',
    serviceSlugs: [],
    notesFr: 'Portail institutionnel de la commune de Tanger.',
    notesAr: 'البوابة المؤسساتية لجماعة طنجة.',
  },
  mavignette: {
    slug: 'mavignette',
    label: 'mavignette.ma',
    domain: 'www.mavignette.ma',
    sourceType: 'tax_authority',
    url: 'https://www.mavignette.ma',
    lastReviewedAt: '2026-03-28',
    serviceSlugs: ['vignette-auto'],
    notesFr: 'Portail de paiement officiel pour la vignette automobile.',
    notesAr: 'بوابة الأداء الرسمية الخاصة برسم السيارات.',
  },
  vignette: {
    slug: 'vignette',
    label: 'vignette.ma',
    domain: 'www.vignette.ma',
    sourceType: 'tax_authority',
    url: 'https://www.vignette.ma',
    lastReviewedAt: '2026-03-28',
    serviceSlugs: ['vignette-auto'],
    notesFr: "Portail officiel de téléchargement de l'attestation de paiement.",
    notesAr: 'البوابة الرسمية لتحميل شهادة الأداء.',
  },
}

export const sourceGroups = {
  official_portal: ['passeport', 'idarati', 'portail', 'watiqa'],
  ministry: ['dgsn', 'justice-casier'],
  city_portal: ['casablanca-city', 'rabat-city', 'tanger-city'],
  tax_authority: ['tax', 'etimfisc', 'mavignette', 'vignette'],
  other_public_body: [],
} as const
